export const TASKS = [
  {
    id: "morning-sky",
    title: "Morning Sky",
    icon: "☀️",
    description: 'আকাশের ছবি তুলে পোস্ট করা এবং "Good Morning, Day X" লেখা।',
    purpose: "To start the day with a positive and public declaration of commitment.",
    category: "starter",
    hasFileUpload: true,
    hasTextInput: false,
  },
  {
    id: "meditation",
    title: "Meditation",
    icon: "⚡",
    description: "টাইমার দিয়ে কমপক্ষে ১০ মিনিট মেডিটেশন করা।",
    purpose: "To cultivate mindfulness and mental clarity.",
    category: "starter",
    hasFileUpload: false,
    hasTextInput: true,
    inputPlaceholder: "minutes",
  },
  {
    id: "hydration",
    title: "Hydration",
    icon: "💧",
    description: "২ লিটার পানি বোতলের ছবি এবং দিনের শেষে খালি বোতলের ছবি পোস্ট করা।",
    purpose: "To ensure proper hydration throughout the day.",
    category: "starter",
    hasFileUpload: true,
    hasTextInput: false,
    multipleFiles: true,
  },
  {
    id: "gratitude",
    title: "Gratitude",
    icon: "🙏",
    description: "চারটি জিনিস আজকের সময় দিনের সবচেয়ে সুন্দর বা gratitudeful মোমেন্টের ছবি পোস্ট করা।",
    purpose: "To practice gratitude and focus on the positive aspects of the day.",
    category: "starter",
    hasFileUpload: true,
    hasTextInput: true,
    inputPlaceholder: "Your notes",
  },
  {
    id: "daily-schedule",
    title: "Daily Schedule",
    icon: "📅",
    description: "প্রতিদিনের কাজের তালিকা তৈরি করে দিনের শেষে আপডেট দেওয়া। Daily Planner ব্যবহার করে।",
    purpose: "To improve planning and accountability.",
    category: "hard",
    hasFileUpload: false,
    hasTextInput: true,
    inputPlaceholder: "Your to-do list for today",
  },
  {
    id: "digital-detox",
    title: "Digital Detox",
    icon: "📵",
    description: "বিকাল ৮টার আগে কোনো সময় অপ্রয়োজনীয় চ্যাটিং না করা।",
    purpose: "To reduce distractions and improve focus during peak hours.",
    category: "hard",
    hasFileUpload: false,
    hasTextInput: true,
    inputPlaceholder: "Mark as complete if you succeeded before 8 PM",
  },
  {
    id: "focused-work",
    title: "Focused Work",
    icon: "🎯",
    description: "কাজের সময় Pomodoro টেকনিক ব্যবহার করা (কমপক্ষে ৪টি)।",
    purpose: "To enhance productivity through focused work intervals.",
    category: "hard",
    hasFileUpload: false,
    hasTextInput: true,
    inputPlaceholder: "Pomodoros",
  },
  {
    id: "reading",
    title: "Reading",
    icon: "📚",
    description: "প্রতিদিন কমপক্ষে ৩০ পৃষ্ঠা বই পড়া এবং তার নোট শেয়ার করা।",
    purpose: "To encourage continuous learning and knowledge acquisition.",
    category: "hard",
    hasFileUpload: true,
    hasTextInput: true,
    inputPlaceholder: "Your notes",
  },
]

export const getTaskById = (id) => {
  return TASKS.find((task) => task.id === id)
}

export const getTasksByCategory = (category) => {
  return TASKS.filter((task) => task.category === category)
}
